spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: employee-service-api-docs
          uri: lb://employee-service
          predicates:
            - Path=/employees/api-docs
          filters:
            - RewritePath=/employees/api-docs, /api-docs
            
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employees/**

        - id: payroll-calculation-service
          uri: lb://payroll-calculation-service
          predicates:
            - Path=/api/v1/payrolls/**

        - id: tax-service
          uri: lb://tax-service
          predicates:
            - Path=/api/v1/taxes/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
